import { useMemo, useState } from "react";
import { ArrowLeft, Check, Pencil, WandSparkles } from "lucide-react";
import SeatLayoutCanvas from "@/features/seat-layout-v3/SeatLayoutCanvas";
import { generateGuidedLayout, type CabinArrangement, type GuidedLayoutConfig, type SeatPattern } from "@/features/seat-layout-v3/generator";
import { passengerPlaces } from "@/features/seat-layout-v3/layout";
import type { SeatLayoutV3 } from "@/features/seat-layout-v3/types";

const arrangements: Array<{ id: CabinArrangement; title: string; detail: string }> = [
  { id: "SINGLE_SEATS", title: "Seats only", detail: "A regular single-level bus" },
  { id: "LOWER_SEATS_UPPER_SLEEPERS", title: "Seats + upper sleepers", detail: "Lower seats with 4–8 upper berths" },
  { id: "SINGLE_SLEEPERS", title: "Sleeper bus", detail: "Full-length sleeper berths" },
];

export default function GuidedLayoutBuilder({ initialConfig, onContinue, onCancel }: { initialConfig: GuidedLayoutConfig; onContinue: (layout: SeatLayoutV3) => void; onCancel: () => void }) {
  const [config, setConfig] = useState(initialConfig);
  const [previewing, setPreviewing] = useState(false);
  const layout = useMemo(() => generateGuidedLayout(config), [config]);

  if (previewing) return <div className="space-y-5"><Header onBack={() => setPreviewing(false)} title="Check the generated layout" detail="If the bus differs, use fine adjustments on the next screen." /><div className="rounded-[24px] bg-[#FAF8F5] p-4"><div className="mb-4 flex items-center justify-between gap-3"><div><p className="font-black text-[#211D1A]">Your starting layout</p><p className="mt-1 text-xs text-[#746E69]">{passengerPlaces(layout).length} passenger places</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-emerald-700">Generated</span></div><SeatLayoutCanvas layout={layout} tool="SELECT" selectedId={null} onSelect={() => undefined} onChange={() => undefined} /></div><button type="button" onClick={() => onContinue(layout)} className="flex h-11 w-full items-center justify-center rounded-xl bg-[#7A1D1B] text-xs font-black text-white"><Pencil className="mr-2 size-4" />Use and make final adjustments</button></div>;

  return <div className="space-y-6"><Header onBack={onCancel} title="Describe this bus" detail="Choose what passengers actually see. We will build the map for you." /><ChoiceGroup label="Passenger arrangement" items={arrangements} value={config.arrangement} onChange={(arrangement) => setConfig({ ...config, arrangement })} /><div className="grid gap-4 sm:grid-cols-2">{config.arrangement !== "SINGLE_SLEEPERS" && <ChoiceGroup label="Seats across each row" items={[{ id: "TWO_BY_TWO" as SeatPattern, title: "2 + 2", detail: "Two seats, aisle, two seats" }, { id: "TWO_BY_ONE" as SeatPattern, title: "2 + 1", detail: "Two seats, aisle, one seat" }]} value={config.seatPattern} onChange={(seatPattern) => setConfig({ ...config, seatPattern })} />}<NumberField label={config.arrangement === "SINGLE_SLEEPERS" ? "Sleeper rows" : "Lower-deck rows"} value={config.lowerRows} min={2} max={20} onChange={(lowerRows) => setConfig({ ...config, lowerRows })} />{config.arrangement === "LOWER_SEATS_UPPER_SLEEPERS" && <NumberField label="Upper sleeper rows" hint={`${config.upperBerthRows * 2} berths`} value={config.upperBerthRows} min={2} max={4} onChange={(upperBerthRows) => setConfig({ ...config, upperBerthRows })} />}</div><div className="rounded-2xl bg-[#FFF6F3] p-4 text-xs leading-5 text-[#6E4B46]">No toilets, luggage areas or emergency equipment are added. You can correct individual seats and sleepers after generation.</div><button type="button" onClick={() => setPreviewing(true)} className="flex h-11 w-full items-center justify-center rounded-xl bg-[#191512] text-xs font-black text-white"><WandSparkles className="mr-2 size-4" />Generate seat map</button></div>;
}

function Header({ onBack, title, detail }: { onBack: () => void; title: string; detail: string }) { return <div className="flex items-start gap-3"><button type="button" onClick={onBack} className="flex size-9 shrink-0 items-center justify-center rounded-xl border border-[#DCD4CD]" aria-label="Go back"><ArrowLeft className="size-4" /></button><div><h4 className="font-black text-[#211D1A]">{title}</h4><p className="mt-1 text-xs text-[#746E69]">{detail}</p></div></div>; }
function ChoiceGroup<T extends string>({ label, items, value, onChange }: { label: string; items: Array<{ id: T; title: string; detail: string }>; value: T; onChange: (value: T) => void }) { return <fieldset><legend className="mb-2 text-[10px] font-black uppercase tracking-[0.16em] text-[#938A82]">{label}</legend><div className="grid gap-3 sm:grid-cols-3">{items.map((item) => <button key={item.id} type="button" onClick={() => onChange(item.id)} className={`relative rounded-2xl border p-4 text-left ${value === item.id ? "border-[#7A1D1B] bg-[#FFF1EE]" : "border-[#E8E1DB] bg-white"}`}><p className="text-sm font-black text-[#211D1A]">{item.title}</p><p className="mt-1 text-xs leading-5 text-[#746E69]">{item.detail}</p>{value === item.id && <Check className="absolute right-3 top-3 size-4 text-[#7A1D1B]" />}</button>)}</div></fieldset>; }
function NumberField({ label, hint, value, min, max, onChange }: { label: string; hint?: string; value: number; min: number; max: number; onChange: (value: number) => void }) { return <label className="rounded-2xl border border-[#E8E1DB] bg-white p-4"><span className="flex items-center justify-between text-xs font-black text-[#211D1A]">{label}{hint && <small className="font-bold text-[#938A82]">{hint}</small>}</span><div className="mt-3 flex items-center gap-3"><button type="button" onClick={() => onChange(Math.max(min, value - 1))} className="size-9 rounded-xl border border-[#DCD4CD] text-lg">−</button><output className="min-w-10 text-center text-xl font-black">{value}</output><button type="button" onClick={() => onChange(Math.min(max, value + 1))} className="size-9 rounded-xl border border-[#DCD4CD] text-lg">+</button></div></label>; }
