"use client";
import { useState } from "react";
import { Armchair, BedDouble, CircleGauge, DoorOpen, Eraser, MousePointer2, Rows3, Save } from "lucide-react";
import { cn } from "@/lib/utils";
import { passengerPlaces, resizeSection, updateElement } from "./layout";
import { layoutPresets } from "./presets";
import SeatLayoutCanvas from "./SeatLayoutCanvas";
import type { BuilderTool, Comfort, LayoutElement, SeatLayoutV3 } from "./types";
const tools: { id: BuilderTool; label: string; icon: typeof MousePointer2 }[] = [{ id: "SELECT", label: "Select", icon: MousePointer2 }, { id: "SEAT", label: "Seat", icon: Armchair }, { id: "BERTH", label: "Sleeper", icon: BedDouble }, { id: "AISLE", label: "Aisle", icon: Rows3 }, { id: "DOOR", label: "Door", icon: DoorOpen }, { id: "DRIVER", label: "Driver", icon: CircleGauge }, { id: "ERASE", label: "Remove", icon: Eraser }];
export default function SeatLayoutBuilder({ layout, onChange, onSave, busy = false }: { layout: SeatLayoutV3 | null; onChange: (layout: SeatLayoutV3) => void; onSave: (layout: SeatLayoutV3) => void; busy?: boolean }) {
  const [tool, setTool] = useState<BuilderTool>("SELECT"); const [selectedId, setSelectedId] = useState<string | null>(null); const selected = layout?.sections.flatMap((section) => section.elements).find((element) => element.elementId === selectedId) || null;
  if (!layout) return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{layoutPresets.map((preset) => <button key={preset.id} type="button" onClick={() => onChange(preset.create())} className="rounded-[28px] border border-[#E8E1DB] bg-white p-6 text-left shadow-sm transition hover:border-[#7A1D1B] hover:shadow-md"><div className="mb-8 flex size-11 items-center justify-center rounded-2xl bg-[#FFF1EE] text-[#7A1D1B]"><Armchair className="size-5" /></div><p className="font-black text-[#191512]">{preset.name}</p><p className="mt-1 text-sm text-[#746E69]">{preset.detail}</p><p className="mt-5 text-[10px] font-black uppercase tracking-widest text-[#7A1D1B]">Use starting point</p></button>)}</div>;
  return <div className="grid gap-5 2xl:grid-cols-[180px_minmax(0,1fr)_290px]"><aside className="rounded-[28px] border border-[#E8E1DB] bg-white p-3"><p className="px-2 py-2 text-[10px] font-black uppercase tracking-[0.2em] text-[#938A82]">Build tools</p><div className="grid grid-cols-2 gap-2 2xl:grid-cols-1">{tools.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => setTool(id)} className={cn("flex items-center gap-2 rounded-xl border px-3 py-2.5 text-xs font-bold", tool === id ? "border-[#7A1D1B] bg-[#FFF1EE] text-[#7A1D1B]" : "border-[#E8E1DB] text-[#655E58] hover:bg-[#FAF8F5]")}><Icon className="size-4" />{label}</button>)}</div></aside><main className="min-w-0"><p className="mb-3 text-xs text-[#817A74]">Lower and upper plans stay side by side. Sleeper berths occupy visible physical length.</p><SeatLayoutCanvas layout={layout} tool={tool} selectedId={selectedId} onSelect={setSelectedId} onChange={onChange} /></main><aside className="space-y-4 rounded-[28px] border border-[#E8E1DB] bg-white p-5"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-[#938A82]">Layout summary</p><p className="mt-2 text-3xl font-black text-[#191512]">{passengerPlaces(layout).length}</p><p className="text-xs text-[#746E69]">reservable passenger places</p></div>{selected && (selected.kind === "SEAT" || selected.kind === "BERTH") ? <ElementEditor element={selected} onChange={(update) => onChange(updateElement(layout, selected.elementId, update))} /> : <div className="rounded-2xl border border-dashed border-[#E8E1DB] p-4 text-xs leading-5 text-[#817A74]">Choose Select, then a seat or berth to edit its label and passenger class.</div>}<div className="space-y-2 border-t border-[#EEE8E2] pt-4">{layout.sections.map((section) => <label key={section.sectionId} className="flex items-center justify-between gap-3 text-xs text-[#655E58]"><span>{section.name} rows</span><input type="number" min={2} max={40} value={section.heightUnits} onChange={(event) => onChange(resizeSection(layout, section.sectionId, Number(event.target.value)))} className="h-8 w-20 rounded-lg border border-[#DCD4CD] px-2" /></label>)}</div><button disabled={busy} onClick={() => onSave(layout)} className="flex h-12 w-full items-center justify-center rounded-xl bg-[#7A1D1B] text-sm font-black text-white disabled:opacity-50"><Save className="mr-2 size-4" />{busy ? "Saving…" : "Save revision"}</button></aside></div>;
}
function ElementEditor({ element, onChange }: { element: LayoutElement; onChange: (update: Partial<LayoutElement>) => void }) { const field = "mt-1 h-10 w-full rounded-lg border border-[#DCD4CD] bg-white px-3 text-xs text-[#191512]"; return <div className="space-y-3 border-t border-[#EEE8E2] pt-4"><p className="text-xs font-black text-[#191512]">Selected {element.kind.toLowerCase()}</p><label className="block text-[10px] font-bold uppercase tracking-wider text-[#938A82]">Passenger label<input value={element.label || ""} onChange={(event) => onChange({ label: event.target.value })} className={field} /></label><label className="block text-[10px] font-bold uppercase tracking-wider text-[#938A82]">Comfort<select value={element.attributes?.comfort} onChange={(event) => onChange({ attributes: { ...element.attributes!, comfort: event.target.value as Comfort } })} className={field}><option>STANDARD</option><option>RECLINING</option><option>SEMI_SLEEPER</option></select></label><label className="block text-[10px] font-bold uppercase tracking-wider text-[#938A82]">Commercial class<select value={element.attributes?.commercialClass} onChange={(event) => onChange({ attributes: { ...element.attributes!, commercialClass: event.target.value as "STANDARD" | "PREMIUM" | "PRIORITY" } })} className={field}><option>STANDARD</option><option>PREMIUM</option><option>PRIORITY</option></select></label><label className="flex items-center gap-2 text-xs text-[#655E58]"><input type="checkbox" checked={element.attributes?.accessible === true} onChange={(event) => onChange({ attributes: { ...element.attributes!, accessible: event.target.checked } })} />Accessible place</label></div>; }
