"use client";
import { BedDouble, CircleGauge, DoorOpen } from "lucide-react";
import { cn } from "@/lib/utils";
import { applyTool } from "./layout";
import type { BuilderTool, LayoutElement, LayoutSection, SeatLayoutV3 } from "./types";
const colors: Record<LayoutElement["kind"], string> = { SEAT: "border-[#C6655D] bg-[#FFF1EE] text-[#722A25]", BERTH: "border-[#7463A5] bg-[#F1EDFF] text-[#463778]", AISLE: "border-[#E8E1DB] bg-[#FAF8F5] text-[#9A9189]", DOOR: "border-emerald-500 bg-emerald-50 text-emerald-700", DRIVER: "border-amber-500 bg-amber-50 text-amber-800" };
function content(element: LayoutElement) { if (element.kind === "BERTH") return <><BedDouble className="size-3.5" />{element.label}</>; if (element.kind === "DOOR") return <DoorOpen className="size-4" />; if (element.kind === "DRIVER") return <CircleGauge className="size-4" />; return element.kind === "AISLE" ? null : element.label; }
function Deck({ section, layout, tool, selectedId, onChange, onSelect }: { section: LayoutSection; layout: SeatLayoutV3; tool: BuilderTool; selectedId: string | null; onChange: (layout: SeatLayoutV3) => void; onSelect: (id: string | null) => void }) {
  const cells = Array.from({ length: section.widthUnits * section.heightUnits }, (_, index) => ({ x: index % section.widthUnits, y: Math.floor(index / section.widthUnits) }));
  return <section className="min-w-0 rounded-[28px] border border-[#E8E1DB] bg-white p-4 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><p className="text-sm font-black text-[#191512]">{section.name}</p><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#938A82]">Front at top</p></div><span className="rounded-full bg-[#FAF8F5] px-2.5 py-1 text-[10px] font-bold text-[#746E69]">{section.elements.filter((e) => e.kind === "SEAT" || e.kind === "BERTH").length} places</span></div>
    <div className="mx-auto grid max-w-[360px] gap-1.5 rounded-[34px] border-2 border-[#DED5CD] bg-[#FCFAF7] p-3" style={{ gridTemplateColumns: `repeat(${section.widthUnits}, minmax(32px, 1fr))`, gridTemplateRows: `repeat(${section.heightUnits}, 38px)` }}>{cells.map(({ x, y }) => <button key={`${x}:${y}`} type="button" aria-label={`Grid ${x + 1}, ${y + 1}`} onClick={() => { const hit = section.elements.find((e) => x >= e.position.x && x < e.position.x + e.size.width && y >= e.position.y && y < e.position.y + e.size.height); if (tool === "SELECT") onSelect(hit?.elementId || null); else onChange(applyTool(layout, section.sectionId, x, y, tool)); }} className="rounded-lg border border-dashed border-[#EDE7E1] hover:border-[#C6655D]" />)}{section.elements.map((element) => <button key={element.elementId} type="button" onClick={() => tool === "SELECT" ? onSelect(element.elementId) : onChange(applyTool(layout, section.sectionId, element.position.x, element.position.y, tool))} className={cn("z-10 flex items-center justify-center gap-1 rounded-lg border text-[10px] font-black shadow-sm transition hover:brightness-95", colors[element.kind], selectedId === element.elementId && "ring-2 ring-[#7A1D1B] ring-offset-2")} style={{ gridColumn: `${element.position.x + 1} / span ${element.size.width}`, gridRow: `${element.position.y + 1} / span ${element.size.height}` }}>{content(element)}</button>)}</div>
  </section>;
}
export default function SeatLayoutCanvas(props: { layout: SeatLayoutV3; tool: BuilderTool; selectedId: string | null; onChange: (layout: SeatLayoutV3) => void; onSelect: (id: string | null) => void }) { return <div className={cn("grid gap-4", props.layout.sections.length > 1 && "xl:grid-cols-2")}>{props.layout.sections.map((section) => <Deck key={section.sectionId} section={section} {...props} />)}</div>; }
