"use client";
import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, Copy, RefreshCw, Send, ShieldCheck } from "lucide-react";
import SeatLayoutBuilder from "@/features/seat-layout-v3/SeatLayoutBuilder";
import { adoptTemplate, assignFleetLayout, createRevision, getFleetAssignment, getLayoutTemplate, listCatalog, listFleets, listMyLayouts, requestFleetLayoutChange, submitRevision } from "@/features/seat-layout-v3/api";
import type { SeatLayoutTemplate, SeatLayoutV3, TemplateDetail } from "@/features/seat-layout-v3/types";

export default function SeatLayoutsPage() {
  const [catalog, setCatalog] = useState<SeatLayoutTemplate[]>([]); const [mine, setMine] = useState<SeatLayoutTemplate[]>([]);
  const [selected, setSelected] = useState<TemplateDetail | null>(null); const [layout, setLayout] = useState<SeatLayoutV3 | null>(null);
  const [name, setName] = useState(""); const [code, setCode] = useState(""); const [summary, setSummary] = useState("Updated physical seat arrangement");
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const [fleets, setFleets] = useState<Array<{ fleetId: string; busName: string; busNumber: string }>>([]); const [fleetId, setFleetId] = useState("");
  async function reload(selectId?: string) { const [platform, owned, fleetItems] = await Promise.all([listCatalog(), listMyLayouts(), listFleets().catch(() => [])]); setCatalog(platform); setMine(owned); setFleets(fleetItems); const id = selectId || owned[0]?.id || platform[0]?.id; if (id) await choose(id); }
  async function choose(id: string) { const detail = await getLayoutTemplate(id); setSelected(detail); setName(detail.template.name); setCode(detail.template.templateCode); setLayout(detail.revisions.find((revision) => revision.layout)?.layout || null); }
  useEffect(() => {
    let active = true;
    void Promise.all([listCatalog(), listMyLayouts(), listFleets().catch(() => [])])
      .then(async ([platform, owned, fleetItems]) => {
        if (!active) return;
        setCatalog(platform); setMine(owned); setFleets(fleetItems);
        const id = owned[0]?.id || platform[0]?.id;
        if (!id) return;
        const detail = await getLayoutTemplate(id);
        if (!active) return;
        setSelected(detail); setName(detail.template.name); setCode(detail.template.templateCode);
        setLayout(detail.revisions.find((revision) => revision.layout)?.layout || null);
      })
      .catch((error) => { if (active) setMessage(error instanceof Error ? error.message : "Unable to load layouts."); });
    return () => { active = false; };
  }, []);
  async function adopt() { if (!selected || selected.template.scope !== "PLATFORM") return; setBusy(true); try { const result = await adoptTemplate(selected.template.id, name.trim(), code.trim()); await reload(result.template.id); setMessage("Template copied into your private operator library."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to adopt template."); } finally { setBusy(false); } }
  async function save(value: SeatLayoutV3) { if (!selected || selected.template.scope !== "OPERATOR") return; setBusy(true); try { await createRevision(selected.template.id, value, summary.trim()); await choose(selected.template.id); setMessage("New immutable draft created. Existing fleet layouts are unchanged."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save revision."); } finally { setBusy(false); } }
  async function submit() { const draft = selected?.revisions.find((revision) => revision.status === "DRAFT"); if (!selected || !draft) return; setBusy(true); try { await submitRevision(selected.template.id, draft.id); await choose(selected.template.id); setMessage("Revision submitted for Shuvmarg review."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to submit."); } finally { setBusy(false); } }
  async function assign() { const revision = selected?.revisions.find((item) => item.status === "PUBLISHED"); if (!selected || !revision || !fleetId) return; setBusy(true); try { const current = await getFleetAssignment(fleetId); if (current.assignment) await requestFleetLayoutChange(fleetId, revision.id); else await assignFleetLayout(fleetId, revision.id); setMessage(current.assignment ? "Fleet layout change sent for review. Current trips remain unchanged." : "Published layout assigned to the fleet."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to assign fleet layout."); } finally { setBusy(false); } }
  const input = "mt-2 h-11 w-full rounded-xl border border-[#DCD4CD] bg-white px-3 text-sm font-semibold text-[#191512] outline-none focus:border-[#7A1D1B]";
  return <div className="min-h-full bg-[#FAF8F5] p-5 lg:p-8"><div className="mx-auto max-w-[1500px] space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#7A1D1B]">Fleet setup</p><h1 className="mt-2 text-4xl font-black tracking-tight text-[#191512]">Seat layout studio</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#746E69]">Start from a Shuvmarg template, keep your own private copy, and submit only physical changes for review.</p></div><div className="rounded-2xl bg-[#FFF1EE] px-4 py-3 text-xs font-bold text-[#7A1D1B]"><ShieldCheck className="mr-2 inline size-4" />Running trips keep their captured layout</div></header>
    <div className="grid gap-5 xl:grid-cols-[300px_minmax(0,1fr)]"><aside className="space-y-4"><LibraryList title="Shuvmarg templates" items={catalog} active={selected?.template.id} onChoose={choose} /><LibraryList title="My layouts" items={mine} active={selected?.template.id} onChoose={choose} /></aside><main className="min-w-0 space-y-5">{selected ? <><section className="rounded-[28px] border border-[#E8E1DB] bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-[1fr_220px_auto]"><label className="text-[10px] font-black uppercase tracking-widest text-[#938A82]">Layout name<input value={name} onChange={(event) => setName(event.target.value)} disabled={selected.template.scope === "OPERATOR"} className={input} /></label><label className="text-[10px] font-black uppercase tracking-widest text-[#938A82]">Private code<input value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} disabled={selected.template.scope === "OPERATOR"} className={input} /></label><div className="flex items-end">{selected.template.scope === "PLATFORM" ? <button onClick={adopt} disabled={busy} className="flex h-11 items-center rounded-xl bg-[#7A1D1B] px-5 text-sm font-black text-white"><Copy className="mr-2 size-4" />Copy to my library</button> : <span className="flex h-11 items-center rounded-xl bg-emerald-50 px-4 text-xs font-bold text-emerald-700"><CheckCircle2 className="mr-2 size-4" />Private operator layout</span>}</div></div>{selected.template.scope === "OPERATOR" && <label className="mt-4 block text-[10px] font-black uppercase tracking-widest text-[#938A82]">What changed?<input value={summary} onChange={(event) => setSummary(event.target.value)} className={input} /></label>}</section><SeatLayoutBuilder layout={layout} onChange={setLayout} onSave={save} busy={busy} />
      {selected.template.scope === "OPERATOR" && <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-[28px] border border-[#E8E1DB] bg-white p-5"><div className="flex items-center gap-2"><RefreshCw className="size-4 text-[#7A1D1B]" /><h2 className="font-black">Revision history</h2></div><div className="mt-4 space-y-2">{selected.revisions.map((revision) => <div key={revision.id} className="flex items-center justify-between rounded-2xl bg-[#FAF8F5] p-4"><div><p className="text-sm font-black">Revision {revision.revisionNumber}</p><p className="text-xs text-[#746E69]">{revision.totalPlaces} places · {revision.status.replaceAll("_", " ")}</p></div>{revision.status === "DRAFT" && <button onClick={submit} disabled={busy} className="rounded-xl bg-[#191512] px-3 py-2 text-xs font-bold text-white"><Send className="mr-1 inline size-3.5" />Submit</button>}</div>)}</div></div><div className="rounded-[28px] border border-[#E8E1DB] bg-white p-5"><h2 className="font-black">Use on a fleet</h2><p className="mt-1 text-xs leading-5 text-[#746E69]">Only published revisions can be assigned. Changing an existing fleet creates a review request.</p><select value={fleetId} onChange={(event) => setFleetId(event.target.value)} className={input}><option value="">Choose fleet</option>{fleets.map((fleet) => <option key={fleet.fleetId} value={fleet.fleetId}>{fleet.busName} · {fleet.busNumber}</option>)}</select><button onClick={assign} disabled={busy || !fleetId || !selected.revisions.some((item) => item.status === "PUBLISHED")} className="mt-3 flex h-11 w-full items-center justify-center rounded-xl bg-[#7A1D1B] text-sm font-black text-white disabled:opacity-40">Assign published revision<ArrowRight className="ml-2 size-4" /></button></div></section>}
    </> : <div className="rounded-[28px] border border-dashed border-[#DCD4CD] bg-white p-12 text-center text-[#746E69]">Choose a reusable layout to begin.</div>}</main></div></div>{message && <button onClick={() => setMessage(null)} className="fixed bottom-6 right-6 z-50 max-w-sm rounded-2xl bg-[#191512] px-5 py-4 text-left text-sm font-semibold text-white shadow-2xl">{message}</button>}</div>;
}
function LibraryList({ title, items, active, onChoose }: { title: string; items: SeatLayoutTemplate[]; active?: string; onChoose: (id: string) => Promise<void> }) { return <section className="rounded-[28px] border border-[#E8E1DB] bg-white p-3 shadow-sm"><p className="px-3 py-3 text-[10px] font-black uppercase tracking-[0.2em] text-[#938A82]">{title}</p>{items.length ? items.map((item) => <button key={item.id} onClick={() => void onChoose(item.id)} className={`mb-2 w-full rounded-2xl border p-4 text-left transition ${active === item.id ? "border-[#7A1D1B] bg-[#FFF1EE]" : "border-transparent bg-[#FAF8F5] hover:border-[#DCD4CD]"}`}><p className="text-sm font-black text-[#191512]">{item.name}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-widest text-[#938A82]">{item.templateCode} · {item.vehicleCategory}</p></button>) : <p className="px-3 pb-4 text-xs text-[#938A82]">Nothing here yet.</p>}</section>; }
