"use client";
import { useState } from "react";
import { useSearchParams } from "next/navigation";
import { useOperatorSession } from "@/features/operator-dashboard/SessionContext";
import { nepalToday, type BookingList, type OwnerBooking, type TripManifest } from "./api";
import { useOwnerResource } from "./use-owner-resource";
import { WorkspaceHeader, ReadStatus, Pagination, panel, input, button, money } from "./WorkspaceUI";
export default function BookingsWorkspace() {
  const search = useSearchParams(), { dashboardState, loading: sessionLoading } = useOperatorSession();
  const [filters, setFilters] = useState(() => ({ from: search.get("from") || nepalToday(), to: search.get("to") || nepalToday(), status: "", page: 1 }));
  const [manifestId, setManifestId] = useState<string | null>(null);
  const [manifestPage, setManifestPage] = useState(1);
  const [selected, setSelected] = useState<string | null>(null);
  const allowed = dashboardState?.verificationStatus === "approved";
  const params = new URLSearchParams({ from: filters.from, to: filters.to, page: String(filters.page), limit: "25" });
  if (filters.status) params.set("status", filters.status);
  if (search.get("tripId")) params.set("tripId", search.get("tripId")!);
  const list = useOwnerResource<BookingList>(allowed ? `/busowner/bookings?${params}` : null);
  const detail = useOwnerResource<OwnerBooking>(allowed && selected ? `/busowner/bookings/${selected}` : null);
  const manifest = useOwnerResource<TripManifest>(allowed && manifestId ? `/busowner/trip-manifest/${manifestId}?page=${manifestPage}&limit=100` : null);
  return <div className="space-y-6"><WorkspaceHeader title="Bookings" description="Passenger bookings for the selected departure dates in Nepal.">{search.get("tripId") && <button className={button} onClick={() => { setManifestId(search.get("tripId")); setManifestPage(1); }}>Departure manifest</button>}</WorkspaceHeader>{!allowed ? <p className={panel}>{sessionLoading ? "Loading verification…" : "Business approval is required to view bookings."}</p> : <>
    <div className="flex flex-wrap gap-3"><label className="text-xs">From<input aria-label="Departure date from" type="date" className={`${input} ml-2`} value={filters.from} onChange={event => setFilters({ ...filters, from: event.target.value, page: 1 })} /></label><label className="text-xs">To<input aria-label="Departure date to" type="date" className={`${input} ml-2`} value={filters.to} onChange={event => setFilters({ ...filters, to: event.target.value, page: 1 })} /></label><select aria-label="Booking status" className={input} value={filters.status} onChange={event => setFilters({ ...filters, status: event.target.value, page: 1 })}><option value="">All statuses</option>{["booked", "pending", "cancelled", "no_show"].map(status => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select></div><ReadStatus {...list} />
    {list.data && <><section className={`${panel} overflow-auto`}><table className="w-full text-left text-sm"><thead><tr><th className="py-3">Ticket</th><th>Departure / route</th><th>Seats</th><th>Status</th><th>Recorded amount</th><th>Actions</th></tr></thead><tbody>{list.data.items.map(booking => <tr key={booking._id} className="border-t border-[#EEE8E2]"><td className="py-3 font-bold">{booking.ticketId}</td><td>{new Date(booking.trip.tripDate).toISOString().slice(0, 10)} · {booking.trip.departureTime}<p className="text-xs text-[#746E69]">{booking.trip.directionLabel || "Route unavailable"}</p></td><td>{booking.seats.join(", ")}</td><td>{booking.status.replaceAll("_", " ")}</td><td>{money(booking.totalAmount)}</td><td><button className={button} onClick={() => setSelected(booking._id)}>Details</button> <button className={button} onClick={() => { setManifestId(booking.trip._id); setManifestPage(1); }}>Manifest</button></td></tr>)}</tbody></table>{!list.data.items.length && <p className="py-4 text-sm">No bookings match these filters.</p>}</section><Pagination page={filters.page} totalPages={list.data.pagination.totalPages} onChange={page => setFilters({ ...filters, page })} /></>}
    {manifestId && <section className={panel}><div className="flex justify-between"><h2 className="font-black">Departure manifest · Active booked passengers</h2><button className={button} onClick={() => setManifestId(null)}>Close manifest</button></div><ReadStatus {...manifest} />{manifest.data && <><p className="my-3 text-sm">{manifest.data.trip.tripDate.slice(0, 10)} · {manifest.data.trip.departureTime} · {manifest.data.trip.directionLabel || "Route unavailable"}</p><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Ticket</th><th>Seats</th><th>Passengers / contact</th><th>Boarding</th></tr></thead><tbody>{manifest.data.items.map(booking => <tr key={booking._id} className="border-t border-[#EEE8E2]"><td className="py-3">{booking.ticketId}</td><td>{booking.seats.join(", ")}</td><td>{booking.passengerDetails?.map((person, index) => <p key={index}>{person.name} · {person.seatNo} · {person.phone || "Contact unavailable"}</p>)}</td><td>{booking.boardingConfirmed ? "Confirmed" : "Not boarded"}</td></tr>)}</tbody></table></div>{!manifest.data.items.length && <p className="my-3 text-sm">No active bookings for this departure.</p>}<Pagination page={manifestPage} totalPages={manifest.data.pagination.totalPages} onChange={setManifestPage} /></>}</section>}
    {selected && <section className={panel}><div className="flex justify-between"><h2 className="font-black">Ticket details</h2><button className={button} onClick={() => setSelected(null)}>Close</button></div><ReadStatus {...detail} />{detail.data && <><p className="mt-3 text-sm">{detail.data.ticketId} · {detail.data.status} · {money(detail.data.totalAmount)} · {detail.data.boardingConfirmed ? "Boarding confirmed" : "Not boarded"}</p><table className="mt-4 w-full text-left text-sm"><thead><tr><th>Name</th><th>Seat</th><th>Contact</th></tr></thead><tbody>{detail.data.passengerDetails?.map((passenger, index) => <tr key={index}><td className="py-2">{passenger.name}</td><td>{passenger.seatNo}</td><td>{passenger.phone || "Unavailable"}</td></tr>)}</tbody></table>{detail.data.refund && <p className="mt-3 text-sm">Refund: {detail.data.refund.status} · {money(detail.data.refund.refundAmount)} · Cancellation charge {money(detail.data.refund.cancellationCharge)}</p>}</>}</section>}
  </>}</div>;
}
