"use client";
import { useState } from "react";
import Link from "next/link";
import type { OperatorDashboardState } from "@/features/operator-dashboard/operator-dashboard-contract";
import { nepalToday, type OwnerOverview } from "./api";
import { useOwnerResource } from "./use-owner-resource";
import { WorkspaceHeader, Metric, ReadStatus, panel, input, money } from "./WorkspaceUI";
export default function OperatingOverview({ state }: { state: OperatorDashboardState }) {
  const [date, setDate] = useState(nepalToday);
  const { data, loading, error } = useOwnerResource<OwnerOverview>(`/busowner/overview?date=${date}`);
  const unfinished = state.fleet.items.filter(fleet => !state.fleetSetupStatusesByFleetId[fleet.fleetId]?.isFullyOperational);
  return <div className="space-y-6"><WorkspaceHeader title="Daily overview" description="Tickets and booking sales for departures on the selected Nepal service date."><label className="text-xs">Service date<input aria-label="Service date" className={`${input} ml-2`} type="date" value={date} onChange={event => { if (event.target.value) setDate(event.target.value); }} /></label></WorkspaceHeader><ReadStatus loading={loading} error={error} />
    {data && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Departures" value={data.summary.departures} /><Metric label="Tickets booked" value={data.summary.ticketsSold} /><Metric label="Active booking sales" value={money(data.summary.bookingSales)} /><Metric label="Seats with bookings" value={data.summary.occupancyPct === null ? "Unavailable" : `${data.summary.occupancyPct}%`} /></div><p className="text-xs text-[#746E69]">{data.date} · {data.timezone}. Includes active booked tickets; pending, cancelled and no-show bookings are excluded. Seats with bookings counts each seat once per departure, including reuse on different route segments; it is not segment occupancy. Booking sales are separate from collected payments and net payouts.</p>
      <section className={panel}><h2 className="font-black">Departures</h2>{!data.departures.length ? <p className="mt-3 text-sm text-[#746E69]">No departures on this date.</p> : <div className="mt-3 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th className="py-3">Bus / route</th><th>Time</th><th>Status</th><th>Tickets</th><th>Booking sales</th><th /></tr></thead><tbody>{data.departures.map(trip => <tr key={trip._id} className="border-t border-[#EEE8E2]"><td className="py-3"><Link className="font-bold text-[#7A1D1B]" href={`/dashboard/fleet/${trip.busId?._id || ""}`}>{trip.busId?.busName || trip.busId?.busNumber || "Bus unavailable"}</Link><p className="text-xs text-[#746E69]">{trip.directionLabel || "Route unavailable"}</p></td><td>{trip.departureTime}</td><td>{trip.status}</td><td>{trip.ticketsSold}</td><td>{money(trip.totalRevenue || 0)}</td><td><Link className="text-[#7A1D1B] underline" href={`/dashboard/bookings?tripId=${trip._id}&from=${date}&to=${date}`}>Bookings</Link></td></tr>)}</tbody></table></div>}</section>
      <section className={panel}><h2 className="font-black">Latest bookings for these departures</h2>{data.recentBookings.length ? <ul className="mt-3 space-y-2">{data.recentBookings.map(booking => <li key={booking._id} className="flex flex-wrap justify-between gap-2 text-sm"><span>{booking.ticketId} · {booking.seats.length} seats · {booking.status.replaceAll("_", " ")}</span><span>{money(booking.totalAmount)}</span></li>)}</ul> : <p className="mt-3 text-sm">No bookings recorded for these departures.</p>}</section>
      {!!data.attention.length && <section className={panel}><h2 className="font-black">Needs attention</h2><ul className="mt-3 space-y-2">{data.attention.map((issue, index) => <li key={`${issue.tripId}-${index}`}><Link className="text-sm text-[#7A1D1B] underline" href={`/dashboard/fleet/${issue.fleetId}`}>{issue.message}</Link></li>)}</ul></section>}</>}
    {!!unfinished.length && <section className={panel}><h2 className="font-black">Buses still needing setup</h2><div className="mt-3 space-y-2">{unfinished.map(fleet => <Link key={fleet.fleetId} href={`/dashboard/fleet/${fleet.fleetId}`} className="flex justify-between gap-3 text-sm"><span>{fleet.busName} · {fleet.busNumber}</span><span className="text-[#7A1D1B]">{fleet.approvalStatus === "APPROVED" ? "Resume launch setup" : fleet.approvalStatus}</span></Link>)}</div></section>}
  </div>;
}
